### ISSUE TITLE
Multiple edges per output

### ISSUE THREAD

**Issue by JakeCoxon** [aphex-/BrotherhoodOfNode#3]
Hi I'm working on a procedural generation editor and I started to write my own node editor. But frankly mine sucks and yours is way better so I'd like to convert over to yours.

One thing I need though is the ability to link two edges to an output which I don't think BoN supports?

<img width="739" alt="screen shot 2016-08-15 at 17 38 58" src="https://cloud.githubusercontent.com/assets/601264/17662421/8611bdb4-630f-11e6-99b5-a9d0969e747a.png">

Is this something you want in Bon? I think this makes sense for all nodes. In your arithmetic example, there's no reason why I shouldn't be able to link the output of an operator to both a display and another node. I'm happy to share ideas and contribute some code

**Comment by aphex-** [comment]
Hey Jake thank you for the idea. I did not add the option to link a socket with two edges manly because of two reasons. 
It makes it a bit confusing in terms of UI.. which edge do you pick if you click on it.
What's more important for me that it's not clear what it does.. is the data of the edkes added, multiplier or mixed or what. What is the behaviour if the edge is not of type number but color?
I think it is better to avoid multiple edges per socket.
Use a "operator" node for input sockets and a "multi" node for output sockets.

**Comment by JakeCoxon** [comment]
Hi, what I'm proposing is that only _output sockets_ can have multiple edges. This means that if the data in the output socket is Color.blue then Color.blue gets sent to every connection. This doesn't affect input sockets which can only have one connection (e.g AbsNode cannot arbitrarily support multiple inputs). As you can see in my example the merge node has two inputs, this is because the node itself has to support the merging on data.

As for UI, the way I have it is that when you select an input socket, it always starts to create a new connection even if there is already a connection there. If you wish to unlink a connection you choose the output socket of the link to select it and then click the background to delete it. But this is an implementation detail that I'm happy to change. 

Just for reference, here are some other node editors that support multiple connections per outputs: https://code.blender.org/wp-content/uploads/2012/05/funky_selection_theme_colors.png http://i.imgur.com/I3rDd7Y.jpg https://orange.blender.org/wp-content/themes/orange/images/blog/noodles.jpg?d9bac0

I understand that it makes the code a bit more complex but I think it would be a useful addition

**Comment by aphex-** [comment]
Multiple edges for output sockets could be useful and is nice to have.  I would fix the edge picking issue like this: Click on the socket, drag it.. if it is not the edge you where looking for repeat. On repeat the socket returns the next edge.
In the serialization logic of BON only edges of the input or the output sockets are serialized (don't know without looking at the code). If we have multiple edges per output we have to make sure the output socket is taken for this serialization.
Feel free to implement this stuff.. otherwise wait until I decide to :)

**Comment by PassivePicasso** [comment]
Just to be sure I'm following you, when you're both saying edges, I'm assuming you're referring to the links between nodes.
If that is correct, what I've seen a lot of other node graphs do for this is as follows:
When you click on an output edge, you start a new link and then you click on an input edge to create the link.
If you want to move or remove a link, you click on the input edge and either click into empty space or on a different input edge.

If this isn't what you're referring to, please kindly ignore my comment!

**Comment by aphex-** [comment]
I am not a native english speaker as you might noticed :) I decided for the word 'edge' because it is used in graph theory. Let me know if I use the wrong terminology somewhere in the project.

Your guys suggestion for this detail is: Drag from an output Socket always starts an new Edge. Drag from an input Socket always disconnects a connected Edge.

As I said earlier we also need to handle multiple sockets in the serialization logic of the graph.

I think implementing this would be a good practice for someone who wants to get into the code. So I will implement other stuff and wait if somebody contributes.

**Comment by PassivePicasso** [comment]
I honestly hadn't noticed.  I don't know graph theory really, so if that's the terminology used then it's probably the best name, and don't listen to my layman's interpretation :D

I know you have a merge waiting, I can look into this once you get it all setup and see how clear it is to me to move forward.

**Comment by aphex-** [comment]
I am currently implementing multiple output Edges per Socket. There are more changes to make than I thought.

**Comment by aphex-** [comment]
Okey guys.. I added the feature (amongst others). Let me know if I broke something.
