### ISSUE TITLE
how to get data in and out

### ISSUE THREAD

**Issue by robotfunk** [aphex-/BrotherhoodOfNode#7]
I'd like to know how I can set/get node values from an external MonoBehaviour.

**Comment by aphex-** [comment]
Hello robotfunk. Could you be more precise? 
If you are writing an MonoBehaviour and want to modify the nodes of a graph you just need to get the **Graph** instance. For example you can get subscribe to the **OnCreateGraph** event as seen in the documentation.

**Comment by robotfunk** [comment]
Hi aphex-, I'm looking for info on how to change values to input and output sockets inside custom nodes. The closest I found was SetDirectInputNumber but I need to change other data types as well.

**Comment by aphex-** [comment]
The **SetDirectInputNumber** sets a number directly to an **InputSocket** to avoid connecting another **Node** to it. It is a convenience feature for the UI.
Currently nothing else than numbers are supported here. If you want to support e.g. direct strings for that you need to implement it for your self. Note that the direct input number is made persistent if you save the **Graph** as json. You need to do that for your direct input type as well.
It would be easier to write a new **Node** with e.g. a text field to hold your input data. Note that such a **Node** (StringNode) already exists for strings. The annotation **[SerializeField]** in the **StringNode** tells **BON** to make the value persistent. This only works for primitive datatypes.

You could also consider buying [GDI](https://www.assetstore.unity3d.com/en/#!/content/72081) since this is a more advanced version of **BON**. Note that GDI does not contain your requested feature!
